### ISSUE TITLE
Split out modules needing guardedness

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1509] opened 2021-05-30 17:02 UTC
We are now getting errors like
```
Importing module Data.Container.Indexed.FreeMonad using the
--guardedness flag from a module which does not.
when scope checking the declaration
  open import Data.Container.Indexed.FreeMonad using (_⋆C_)
```
I suppose I should not need to turn on `--guardedness` unless I want to use the `M` type.  

Thus, we need to split out modules using `--guardedness` like we do with module using `--with-K`.

Or maybe we shouldn't push such a backwards-incompatible restrictions into the release last minute, @jespercockx ...

On the long run, we want `--guardedness` to be infective, so we need to refactor, but we would have more time and quiet after the release.

**Comment by andreasabel** [comment] 2021-05-30 17:18
https://github.com/agda/agda-stdlib/blob/2da3469a676f3a3e21a5088370c5d16dfcffef1e/src/Data/Container/Indexed/FreeMonad.agda#L7

Does this module really need `--guardedness`?  It only uses the `W`-type, not the `M`-type.  Rather than from `Data.Container.Indexed`, the `W`-type could also be imported from `Data.W.Indexed` and we could confine with `Data.Container.Indexed.Core`.  Both of these do not use `-guardedness`.

**Comment by gallais** [comment] 2021-05-30 19:06
I had assigned myself on #1465 because I wanted to minimise the
contamination but it got merged before I could find the time to
deal with this. This is indeed a very invasive change that
unnecessarily knocks a lot of the library's content to the unsafe
part of the language.

**Comment by jespercockx** [comment] 2021-05-30 19:42
#1465 is related to making --sized-types incompatible with --safe, while the problem here is caused by making --guardedness no longer enabled by default. The relevant PR here is https://github.com/agda/agda/pull/5386.

**Comment by jespercockx** [comment] 2021-05-30 19:43
Sorry, that's the PR on the main Agda repo. The one for the stdlib is https://github.com/agda/agda-stdlib/pull/1504.

**Comment by MatthewDaggitt** [comment] 2021-05-31 13:32
> I had assigned myself on #1465 because I wanted to minimise the
contamination but it got merged before I could find the time to
deal with this. 

@gallais my apologies, I completely missed that you'd assigned yourself to it. I'll do my best to not to miss that again!

As for what we would have to refactor. Searching for `--guardedness` shows there are 4 major sources:
 - Codata.Musical
 - System.Exit
 - IO
 - Data.Container

Firstly which of these is guardedness integral to (presumably not Data.Container from @andreasabel comment above)?

Secondly, for those in which it is not integral, how difficult would be to isolate the code that requires `--guardedness`? I have to confess I'm not terribly familiar with the `Data.Container` submodules...

**Comment by MatthewDaggitt** [comment] 2021-05-31 14:21
FYI, see #1513 which contains similar refactoring.

**Comment by gallais** [comment] 2021-06-01 14:23
> @gallais my apologies, I completely missed that you'd assigned yourself to it. I'll do my best to not to miss that again!

No bother: I'm not as active as I used to be and I still haven't found the time to
look into it.

**Comment by MatthewDaggitt** [comment] 2021-06-03 05:27
@andreasabel right in #1513 I've hopefully fixed your problem by splitting out the greatest fixpoint out of `Data.Container.Indexed` which means that we can remove the guardedness flags throughout those modules.

Having looked at these other cases I've listed above, I think the musical codata and therefore guardedness appears pretty embedded in them so I propose to close this issue once the PR has been merged in.

**Closed** 2021-06-08 11:26 UTC
Labels: dependencies, discussion, library-design, upstream
