### ISSUE TITLE
Proposal for  refl, sym, trans

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#615] opened 2019-02-14 20:52 UTC
I suggest to prefix with ``≈`` the following property names for ``_≈_`` in ``Setoid``: 
``refl, reflexive, sym, trans``.
So that to make them  ``≈refl,  ≈reflexive, ≈sym, ≈trans``.

Motivation: 
user modules often import both  ``_≈_`` of ``Setoid`` and its properties,
and also propositional equality and its properties  ``refl, reflexive, sym, trans``.
And each time the programmer needs to rename these names in order to avoid clash.

**Comment by gallais** [comment] 2019-02-14 20:57
Note that you can import one or the other *qualified* and then use the qualified names.

We often `open import Relation.Binary.PropositionalEquality as P using (_≡_)` in
the stdlib and then use `P.refl` in the rest of the module.

**Comment by mechvel** [comment] 2019-02-14 21:14
``P`` often denotes other things, while ``≈`` is more specific.
In early days I wrote ``PE.refl``. But ``≈refl`` is easier to read.

**Comment by gallais** [comment] 2019-02-14 21:26
My point is that you can use a qualified for your setoid module too and thus pick the
notation you like most. E.g.

```agda
open import Relation.Binary
open import Data.List.Base
open import Data.List.Relation.Binary.Pointwise as Pw using (Pointwise)
open import Relation.Binary.PropositionalEquality as P using (_≡_)

module ≈ {a} {A : Set a} = Setoid (Pw.setoid (P.setoid A))

module _ {a} {A : Set a} {xs : List A} where

  _ : xs ≡ xs
  _ = P.refl

  _ : Pointwise _≡_ xs xs
  _ = ≈.refl
```

**Comment by MatthewDaggitt** [comment] 2019-02-15 10:11
If we were starting the library again from scratch, then yes I'd be in favour of this to improve consistency with the names in the ordered structures.

However I'm afraid this is probably another example of a non-backwards compatible change that is too large to justify for only a cosmetic reason.

**Comment by mechvel** [comment] 2019-02-15 12:15
G. Allais wrote
```
-----------------------------------------------------------
...
private module ≈ {a} {A : Set a} = Setoid (Pw.setoid (P.setoid A))
module _ {a} {A : Set a} {xs : List A} where
  _ : xs ≡ xs
  _ = P.refl

  _ : Pointwise _≡_ xs xs
  _ = ≈.refl
-----------------------------------------------------------
```
Probably, having  a module name ``≈`` and denotation ``≈.refl``, one can then use ``refl`` instead of ``P.refl``.
(?)
Currently I use this:
```
module Setoid-pack {α α=} (A : Setoid α α=)
  where
  open Setoid A using (Carrier; _≈_) 
  ≈refl   = Setoid.refl   A
  ≈sym  = Setoid.sym  A
  ...
  -- there are possible other items for Setoid 
```
Then, having   ``open Setoid-pack setoid``  for any instance ``setoid`` in the scope, there is possible to use ``sym`` for ``_≡_`` and ``≈sym`` for ``_≈_`` in this scope.
My proposal had the aim of  removing the necessity of declaring  ``open Setoid-pack setoid ...`` in each scope.

**Comment by HuStmpHrrr** [comment] 2019-02-17 20:40
sorry I don't understand. why do you need `Setoid-pack`? `Setoid` as a record can readily be used as a module.

**Comment by mechvel** [comment] 2019-02-18 10:39
1.  Because I need to avoid the "renaming" part each time.
I (we) need to use in the same scope ``≈refl, ≈sym ...`` as of Setoid and  ``refl, sym ...`` for propositional equality. To use this, it is  sufficient to set 
``open Setoid-pack setoid-foo`` in each corresponding place.
And with ``open Setoid setoid-foo``, one would need to add each time 
``renaming (refl to ≈refl; sym to ≈sym ...)``.

2. Setoid-pack is still needed in almost any library. 
Because it joins all the items that are defined in the environment of arbitrary Setoid.
Similarly any library that use standard algebra of Agda  would need 
Magma-pack, Semigroup-pack ... Group-pack ... Ring-pack.
For example, there are many usable items for Monoid, that are not implemented inside the Monoid record. Example: it is natural to define  the powering operation ``_^_`` in an arbitrary monoid, and to implement a binary algorithm for it.  With using the standard library of Agda, this needs to be done by introducing ``module Monoid-pack ... (M : Monoid ...)``. 
There are thousands of such types and operations. 

The suffix "-pack" stands for "package". I take the word "package" from the Axiom library for scientific computation. For example,
 "module Monoid-pack ..."  abbreviates   "module ItemsRelatedTo-Monoid ..."

**Comment by gallais** [comment] 2019-02-18 10:54
> Probably, having a module name `≈` and denotation `≈.refl`, one can then use `refl` instead of `P.refl`. (?)

Sure. But I didn't want to seem to claim that one relation has a special status:
all of the modules can be merely `import`ed and assigned a short name which acts
as a disambiguating prefix.

I think it is much nicer to keep name shorts in the stdlib & then import modules
qualified when there may be ambiguities.

**Comment by HuStmpHrrr** [comment] 2019-02-18 18:20
I still don't see the reason. It seems to me it's just `open Setoid some-setoid renaming (refl to some-refl)` is it not?

is that a problem caused by the fact that `refl` is the constructor of propositional equality?

**Comment by MatthewDaggitt** [comment] 2019-03-07 15:35
Closing this, see my general answer in #639

**Closed by MatthewDaggitt** 2019-03-07 15:35 UTC
Labels: breaking, discussion, library-design, status: wontfix
