### ISSUE TITLE
Release v2.1.1

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#2461] opened 2024-08-16 12:49 UTC
Now that it is finally released, we should make sure we're compatible with it (both to see if v2.1 is, and current development/v2.2 is). If memory serves me correctly, neither are - but we should make sure all appropriate wikis are clear about that!

**Comment by JacquesCarette** [comment] 2024-08-16 12:50
(I was looking at what labels to add to this, and didn't see anything that fit all that well?)

**Comment by jamesmckinna** [comment] 2024-08-16 14:40
> Now that it is finally released, we should make sure we're compatible with it (both to see if v2.1 is, and current development/v2.2 is). If memory serves me correctly, neither are - but we should make sure all appropriate wikis are clear about that!

Oh no! 

At least as far as v2.1 is concerned, it should simply be badged as compatible with v2.6.4 (.5?)

But as for v2.2, I'm not quite ready to make the 'great leap forward'... sigh ;-)

**Comment by andreasabel** [comment] 2024-08-16 15:14
Could you release 2.1.1 instead with just the minimal fixes over 2.1 for Agda 2.7.0?  (Some fixes are on the `experimental` branch.)

**Comment by iblech** [comment] 2024-08-19 13:46
I just checked: Just two commits from the experimental branch need to be cherry-picked to tag v2.1 in order to establish compatibility with Agda 2.7.0: 586f56ade1574c83e11f63c4a5139fd24becc95c and 586f56ade1574c83e11f63c4a5139fd24becc95c.

**Comment by MatthewDaggitt** [comment] 2024-08-19 13:52
Yup, I will try get it sorted tomorrow

**Comment by MatthewDaggitt** [comment] 2024-08-20 10:04
Created the first release candidate.

**Comment by MatthewDaggitt** [comment] 2024-08-20 12:17
Second release candidate created

**Comment by mechvel** [comment] 2024-08-21 13:17
I try testing lib-2.1.1-rc2 on my large application.
I type-checks everything. 
But I also test compilation examples to executable.
And this produces ``internal error`` due to a bug in Agda 2.7.0 (see news in the Agda bug tracker).
Therefore I cannot reliably test lib-2.1.1-rc2 before this bug in Agda is fixed.

**Comment by mechvel** [comment] 2024-08-21 13:41
More precisely, it is compiled by a certain sequence of type-check-compile commands and produces "internal error" for another sequence. 
Most probably this effect does depend on the standard library version.

**Comment by andreasabel** [comment] 2024-08-21 14:53
@mechvel wrote:
> And this produces internal error due to a bug in Agda 2.7.0

This refers to 
- https://github.com/agda/agda/issues/7436

One would speculate that it is a regression in the `.agdai` creation.  I do not think it is related to the standard library.

**Comment by jamesmckinna** [comment] 2024-08-24 03:47
Milestone is v2.2.1? Rather than v2.1.1?

**Comment by JacquesCarette** [comment] 2024-08-24 13:41
I think that's just a typo, I'll see if I can fix it.

**Comment by MatthewDaggitt** [comment] 2024-09-03 02:37
I've made the release. @gallais any chance you could generate and upload the website docs? I still can't get it running on my computer :cry:

**Comment by jamesmckinna** [comment] 2024-09-03 09:09
@MatthewDaggitt @gallais I've just tried following the [release-guide.txt instructions](https://github.com/agda/agda-stdlib/blob/master/doc/release-guide.txt#L64-L74), and had several/many problems, so suggest raising a separate `continuous-integration`/`admin` issue? 
In short order, working with the supplied instructions: 
* `cabal run GenerateEverything.hs` should be superseded by `make setup`, since we moved the `Everything*` files to `doc` (also, for my version of `cabal`, it objects, suggesting instead `cabal run GenerateEverything`, which does work, but is out of step with the new destination for the generated files...)
* `git checkout gh-pages` falls over, because of clashes between that branch and, AFAICT, on all the files added/updated since the v2.1 release... did we fail to update the `gh-pages`  branch after the v2.1 release? or is something else broken?

At that point, I bailed...

**Comment by gallais** [comment] 2024-09-03 09:53
It should have landed now: https://agda.github.io/agda-stdlib/

**Comment by jamesmckinna** [comment] 2024-09-03 09:54
Out of interest, @gallais , were you able to diagnose how/why Matthew and I were having problems as above?

**Comment by gallais** [comment] 2024-09-03 10:12
I had similar issues with `cabal` but I do not dare to suggest a solution as everyone seems
to have a different version using a different mechanism to run scripts.

I don't know why the location of the `EverythingX.agda` files would matter given the command
line to generate the html includes all of `-i. -idoc -isrc`. It could be you had stray files left in the
`doc/` directory?

I don't know why anything would fall over when you checkout `gh-pages`.

**Comment by jamesmckinna** [comment] 2024-09-03 12:07
Thanks @gallais I may try a fresh clone after merging #2473 ...

**Comment by jamesmckinna** [comment] 2024-09-07 11:23
I got myself confused as to whether this issue is closed by #2473 or not...

**Comment by MatthewDaggitt** [comment] 2024-09-08 13:43
It was closed by @gallais uploading the release branch :smile:  Rebasing `master` so that it includes the changes from v2.1.1 is not per se part of the release process I think...

**Comment by MatthewDaggitt** [comment] 2024-09-08 13:44
Thanks everyone for their work!

**Closed by MatthewDaggitt** 2024-09-08 13:43 UTC
Labels: upstream
