### ISSUE TITLE
Export `return` from `IO.Primitive`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#2124] opened 2023-10-06 07:46 UTC
Trying to check my development _Type-preserving compilation via dependently typed syntax_ ([SPLS March 2023](https://scottish-pl-institute.github.io/spls/meetings/2023/february/)) with the current standard library, I get a failure for a trivial reason:
```
The module IO.Primitive doesn't export the following:
  return
when scope checking the declaration
  open import IO.Primitive public using (return; _>>=_)
```
In this state, I see no easy way to make my development work with both std-lib 1.7.1/2 and 2.0.

An easy fix would be to restore `return` to this module with the alias `return = pure` which could maybe be coming with a deprecation warning.  
(Though in my view there is no consensus in the FP community that `return` is a bad word and `pure` the good word. Esp. when the `return` statement is the last of my function, it makes perfectly sense to say `return result` rather than `pure result`).

Ref: https://github.com/agda/agda-stdlib/blame/master/src/IO/Primitive.agda

**Comment by gallais** [comment] 2023-10-06 08:42
The issue is that `return` clashes with `case_return_of_`.

**Comment by andreasabel** [comment] 2023-10-06 09:32
@gallais Please have a look at #2125 which adds the backwards-compatibility with v1.7 that I need for an IO-monadic Agda development (the one mentioned in the OP).

**Comment by jamesmckinna** [comment] 2023-10-06 09:56
Suggest instead:
* add the alias `pure = return` to v1.7.2 `IO.Primitive`
* import in a both-versions-compatible way `open import IO.Primitive public using (_>>=_) renaming (pure to return)`

Does that work?

**Comment by jamesmckinna** [comment] 2023-10-10 08:40
The discussion on #2129 seems to be asking for a v1.7.3 (or back-patching v1.7.2). Suggest we lift this out as a separate issue, and collect a number of issues which might be solved by such a thing, together with some discussion/agreement about what (minimal) patches might be necessary? But I do worry that this would be opening a door...

**Comment by MatthewDaggitt** [comment] 2023-10-11 02:41
Given how widely `return` is used, maybe it should be `case_return_of_` whose name should be changed? Thought I don't have any particular suggestions. Just throwing it out there @gallais ?

**Comment by gallais** [comment] 2023-10-11 06:54
Yeah of course but as you said, there are no alternative name proposals (#356).
And on the other hand, should we pollute the namespace with an alias for `pure` just because
Haskell does so? Should we add `fmap` as an alias for `_<$>_` because people may reach for
it out of habit?

**Comment by andreasabel** [comment] 2023-10-12 17:47
> Yeah of course but as you said, there are no alternative name proposals (#356).

`case_yield_of_` would use a synonym of "return".  
In other PLs (except maybe Coq), neither `return` nor `yield` is used for the return _type_, but always for the return _value_.

Also `case_return:_of_` is thinkable with the `:` emphasizing a return _type_.

**Comment by JacquesCarette** [comment] 2023-10-13 14:00
On Zulip, @jamesmckinna suggested `case_returning_of_`. I happen to also like your 'thinkable' suggestion. (i.e. either `returning` or `return:` would feel like an improvement). I don't feel that `yield` is much of an improvement for the very reason you mention: it still feels value-level rather than type-level.

**Comment by Taneb** [comment] 2023-10-13 14:03
I also like `case_returning_of`, I feel it reads fluently

**Comment by jamesmckinna** [comment] 2023-10-16 10:56
I'm pinching myself a little here... is it really the case that the only use(s) of `case... return... of...` in the library are in `Function.Base`? It seems as though *all* other uses are of the derived form `case...of...`, in which case the renaming/deprecation `return` $mapsto `returning` could/would be immediate...?

**Comment by MatthewDaggitt** [comment] 2023-10-16 11:21
Yup, that was what I found as well.

**Comment by MatthewDaggitt** [comment] 2023-10-16 23:21
Which means I guess that we can now allow `return` to make a return. I do think we'll get a lot of complaints if we don't keep it.

**Comment by jamesmckinna** [comment] 2023-10-17 05:41
I'll let others who want ruthenium pick up that particular slack. But I would argue to retain `pure` as well as the factorisation of `Monad` via `Applicative`...

**Comment by jamesmckinna** [comment] 2023-10-17 21:59
Now that #2157 has been merged in, there will need to be an eventual update to the `readthedocs` To reflect this...

**Comment by MatthewDaggitt** [comment] 2023-10-18 01:51
Nice spot!

**Closed** 2023-10-19 01:35 UTC
Labels: library-design, discussion
