### ISSUE TITLE
Unify definitions of divisibility 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1572] opened 2021-08-08 10:27 UTC
lib-1.7 has a general divisibility notion  `_∣_`  for Magma.
But Data.Nat.Divisibility gives  a certain special definition for `_∣_` .
Probably `_|_` for Nat, Integer, Nat.Binary ... needs to be imported as the instance of the generic definition. 
?

**Comment by MatthewDaggitt** [comment] 2021-08-09 01:33
Yes, we will try and fix this in version 2.0.

**Comment by MatthewDaggitt** [comment] 2021-08-11 08:33
Duplicate of #679 so closing.

**Closed by MatthewDaggitt** 2021-08-11 08:33 UTC
Labels: refactoring, breaking
