### ISSUE TITLE
Fix the syntax for symmetric equality reasoning combinator

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda-stdlib#1138] opened 2020-03-31 14:05 UTC
Quoting @MatthewDaggitt 

> I too would like to do something about the ˘ syntax, even though I introduced it 
> I really hate it: it's difficult to type, it ruins the alignment of proofs and doesn't clearly convey symmetry to me. 

Here are a few proposals to get the discussion going:

1. `_↑≡⟨_⟩_` and `_↓≡⟨_⟩_`, stolen from the categories library (at least they used to be there when I used it way back). The arrow indicates the direction in which we are applying the equality.
2. `_↑⟨_⟩_` and `_↓⟨_⟩_` as shorter alternatives.

**Comment by JacquesCarette** [comment] 2020-04-03 15:26
I like the shorter alternatives. If we have to put in the relation wrt which we're working, I'm wondering about putting it in the other order, i.e. `_≡↑⟨_⟩_`.

I think having these as aliases (or the current ones as aliases) could be an interesting experiment. Let a couple of versions go by, and see what people tend to use the most, then deprecate the other.

**Comment by dylanede** [comment] 2020-04-03 22:52
+1 for putting the direction indicator after the relation symbol.

Regarding the direction indicator, would horizontal arrows (of some style) make more sense or be more likely to be confused with the many other uses of horizontal arrows?

**Comment by ajrouvoet** [comment] 2020-04-04 11:43
Equality reasoning proves are usually code-set vertically. :man_shrugging:

**Comment by MatthewDaggitt** [comment] 2020-04-26 02:33
I like the idea of vertical arrows. My only comment is that I also like having the angle brackets aligned on the page, which is one of things that I find very distressing about the current sym notation. This proposal would partially fix it as the sym and non-sym-ed versions would now align, but it still wouldn't align with other operators, e.g. inequalities:
```agda
begin
  (m / n) * n          ≤⟨ ... ⟩
  (m / n) * n + m % n  ≡↑⟨ ... ⟩
  m % n + (m / n) * n  ≡↓⟨ ... ⟩
  m                    ∎
```

Would people hate it if we moved the arrows inside the brackets? i.e.  `_≡⟨↓_⟩_` and `_≡⟨↑_⟩_`
```agda
begin
  (m / n) * n          ≤⟨ ... ⟩
  (m / n) * n + m % n  ≡⟨↑ ... ⟩
  m % n + (m / n) * n  ≡⟨↓ ... ⟩
  m                    ∎
```

**Comment by WolframKahl** [comment] 2020-04-26 02:41
Yes.        :wink:

If you want them inside, you can also define `↓_ = ≡-sym` with appropriate low precedence.

Having the arrows after the closing hint bracket looks more acceptable to me:
```
begin
  (m / n) * n          ≤⟨ ... ⟩
  (m / n) * n + m % n  ≡⟨ ... ⟩↑
  m % n + (m / n) * n  ≡⟨ ... ⟩↓
  m                    ∎
```
Or, even better: :wink:
```
begin
  (m / n) * n          ≤⟨ ... ⟩
  (m / n) * n + m % n  ≡⟨ ... ⟩
  m % n + (m / n) * n  ≡⟨ ... ⟩˘
  m                    ∎
```

**Comment by JacquesCarette** [comment] 2020-04-26 12:58
I also would dislike the arrows inside the brackets. Having them after is better than inside [though not necessarily the best choice].

**Comment by gallais** [comment] 2020-04-26 17:58
A trailing character at the far right of the line is easy to miss. We dismissed
this possibility last time around for this reason.

What about a modified `≡`? I see `⩧` ("identical with dot above") exists.

Or if we want to merge the idea of an arrow and an equality sign, we have the
pair `≙` and `≚` that could play this role and still be only 1 character. I am not
too happy about the fact that they are not derived from `≡` though. :disappointed:

**Comment by ajrouvoet** [comment] 2020-05-07 10:42
> I am not too happy about the fact that they are not derived from ≡ though

Yeah I think using different symbols to denote the same equality is more confusing than necessary.

**Comment by ajrouvoet** [comment] 2020-05-07 19:05
Oh, that is embarrassing, there is standard notation for this!

```
_≡⟨╯°□°╯︵┻━┻_⟩_
```

**Comment by jamesmckinna** [comment] 2022-09-20 09:41
A (perhaps mischievous) thought:
* left-to-right rewriting by an equation `_≡⟩_⟩_`
* right-left rewriting `_≡⟨_⟩_`
The tragedy is that it clashes with our existing conventions (sigh ;-)), but it has always seemed to me a cognitive overload to insist that `\langle,\rangle` function merely as parentheses, on top of which we then overlay an addtional directional indicator: they're directional already!

**Comment by jamesmckinna** [comment] 2022-10-26 06:35
On second thoughts, it seems that I prefer to *reverse* the 'bracket orientation':
* '_>_>_' for LHS to RHS appeal to an equation
* '_<_<' for the 'sym' direction...

**Comment by MatthewDaggitt** [comment] 2023-04-26 07:21
> On second thoughts, it seems that I prefer to reverse the 'bracket orientation':
> 
>   `_≡⟩_⟩_` for LHS to RHS appeal to an equation
>   `_≡⟨_⟨_` for the sym direction...

I *really* like this suggestion :+1:  The only one I've seen I'd be happy implementing! And it would be backwards compatible as we could leave the old names in place.

**Comment by JacquesCarette** [comment] 2023-04-26 08:43
I could definitely warm up to this too.

**Comment by Taneb** [comment] 2023-04-26 08:57
I'd want to check how it interacts with emacs' parenthesis-matching tools; I think `⟨` and `⟩` count as parentheses for that, and this suggestion would interact badly there.

**Comment by gallais** [comment] 2023-05-15 07:51
Looking at Orestis' talk this morning, I realise we could do the following:
```
begin
  (m / n) * n          ≤⟨ ... ⟩
  (m / n) * n + m % n  ≡⟨ ... ⟫
  m % n + (m / n) * n  ≡⟪ ... ⟩
  m                    ∎
  ```

**Comment by MatthewDaggitt** [comment] 2023-10-13 00:56
The problem is that @gallais suggestion would also interact badly with a parens matching algorithm. To be honest I'm not very convinced that the parens matching problem is really a huge issue. It must be configurable for which unicode symbols it counts as paranethesis. There are so many of them that could definition be used for other purposes apart from parens.

My vote would be to implement @jamesmckinna 's suggestion v2.0. The only change I'd suggest is that we have:
```agda
_≡⟨_⟩_ for LHS to RHS appeal to an equation
_≡⟨_⟨_ for the sym direction...
```
so that only the right most paren would indicate direction. This would have two minor advantages. Firstly, we'd only change the sym operator and not the main operator. Secondly, the main operator would still interact nicely with parens matching, so if people wanted to prioritise matching parens they could always just apply `sym` manually!

**Comment by WolframKahl** [comment] 2023-10-13 02:12
If vertical alignment is the problem, then you can always get that for example by inserting a "visible space":
````
_≡␣⟨_⟩_
_≡˘⟨_⟩_
````
I prefer this since I like to think of the angle brackets as "hint brackets" delimiting the justification for the relationship via `_≡_` respectively `_≡˘_` between the expression on the previous line and the one on the next, assuming long vertical layout:
````
   E₁
 ≡␣⟨ H₁ ⟩
   E₂
 ≡˘⟨ H₂ ⟩
   E₃
````
Since not all uses of calculational presentation will involve symmetric relations, I think that just keeping the whole relation in front of the hint brackets is more consistent.

(Many informal users of calculational presentation, as well as [CalcCheck](http://CalcCheck.McMaster.ca), allow an arbitrary number of spaces between the relation and the hint opening bracket; this can also be used to achieve vertical alignment:
````
   E₁
 ≡   ⟨ H₁ ⟩
   E₂
 ≡˘  ⟨ H₂ ⟩
   E₃
````
)

**Comment by MatthewDaggitt** [comment] 2023-10-13 02:28
Thanks for the interesting suggestion and context @WolframKahl!

> If vertical alignment is the problem, then you can always get that for example by inserting a "visible space":

Unfortunately, vertical alignment is just one of the issues. The other two issues included at the top of this issue are "difficulty to type" and "convey the notion of symmetry/direction". We're also looking ideally for something that doesn't involve us renaming the existing standard operator.

> Since not all uses of calculational presentation will involve symmetric relations, I think that just keeping the whole relation in front of the hint brackets is more consistent.

I agree, which is why I think we shouldn't change the forward direction combinator so that we don't have any effects on non-symmetric theories.

**Comment by MatthewDaggitt** [comment] 2023-10-13 02:29
To be honest the more I think about it, the more I'm on board with `_≡⟨_⟨_`. It:
- conveys direction
- preserves vertical alignment
- doesn't require renaming the forward direction
- is easy to type

I think we're going to be hard pressed to beat that!

**Comment by jamesmckinna** [comment] 2023-10-17 12:06
Regarding parenthesis matching (of which, in `emacs`, I am entirely ignorant), note that, thanks to whitespace discipline in `agda`, the L/R parenthesis pairs (under my 2.0 proposal) are, in lexical terms:
* for forward reasoning, `≡⟩` and `⟩`
* for backwards, `≡⟨` and `⟨`

and those pairs are unambiguous for the lexer, by contrast with forward reasoning in terms of `≡⟨` and `⟩`...

**Closed** 2023-10-19 00:40 UTC
Labels: discussion, naming
