### ISSUE TITLE
top-level README.agda (and Everything.agda)

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1743] opened 2022-03-25 20:02 UTC
Over in agda-categories we have https://github.com/agda/agda-categories/issues/342 which is about `Everything.agda` that's in the repo but doesn't typecheck.

The situation is different in stdlib: `Everything.agda` is generated for the doc, but not in the repo. `README.agda` is, however, in. It has the same problem, in that it doesn't typecheck where it is (AFAIK).

I'm not quite sure what to do about it. But likely the same 'solution' is likely to apply to both libraries - thus this issue.

**Comment by MatthewDaggitt** [comment] 2022-03-25 20:10
Err so my solution is to add `.` to the end of this line whenever I want to type-check the README directory:
https://github.com/agda/agda-stdlib/blob/1d0965c7d901212a0bbdd3c673787d32d7e30882/standard-library.agda-lib#L2

I'm not sure there's a better solution available at the moment. Really we need a different field than `include` in the `agda-lib` files. Maybe we can convince @wenkokke to add one in while she's addressing https://github.com/agda/agda/issues/5553?

**Comment by gallais** [comment] 2022-03-25 20:19
Related: #827

**Comment by wenkokke** [comment] 2022-03-26 19:04
Maybe we should split into “public” and “private”? @gallais?

**Comment by gallais** [comment] 2022-03-26 19:18
I expect we will want to ensure that private modules do not leak into public ones.
That's quite a bit of work on top refactoring all of the config files. :D

**Comment by MatthewDaggitt** [comment] 2022-03-26 19:20
That's true. Okay, I rescind my suggestion that we should try and convince you to do it _while_ doing the refactoring!

**Comment by wenkokke** [comment] 2022-03-27 00:27
> I expect we will want to ensure that private modules do not leak into public ones.
> That's quite a bit of work on top refactoring all of the config files. :D

Why? I just expect them to be unimportable, but if a public module in the same package chooses to reexport it, that’s fine?

**Comment by JacquesCarette** [comment] 2022-03-27 13:24
I don't necessarily see the problem as `README.agda` not typechecking where it is, but being in the repo at all: it's a generated file. It's useful to generate the web site, but really shouldn't be checked in.

The `README` directory is a different thing, I agree. It almost feels like `README` should be its own library? [I wouldn't want to put it in a different repo.]

**Comment by wenkokke** [comment] 2022-03-28 10:05
The `README` isn’t generated, is it? That’s `Everything.agda`?

**Comment by wenkokke** [comment] 2022-03-28 10:06
> I don't necessarily see the problem as `README.agda` not typechecking where it is, but being in the repo at all: it's a generated file. It's useful to generate the web site, but really shouldn't be checked in.
> 
> The `README` directory is a different thing, I agree. It almost feels like `README` should be its own library? [I wouldn't want to put it in a different repo.]

Having things such as `README` and `Everything` live in a separate library would be an easy solution.

**Comment by gallais** [comment] 2022-03-28 14:06
> Having things such as README and Everything live in a separate library would be an easy solution.

The annoying thing with this solution is that `README.agda` then needs to be moved to a subdirectory
because Agda does not like (for good reasons) having 2 `.agda-lib` files in the same directory.

**Comment by jamesmckinna** [comment] 2022-03-28 14:39
...or: have an alias in your path (does `agda2-mode` allow switching to such a 'version') to `agda -i .` for such eventualities (and avoid having to worry about 'standard' `.agda-lib` setups)?

off-topic (ish), but related: should the `agda` invocation in the stdlib `GNUmakefile` not also take the `--no-default-libraries` flag when checking the stdlib?

**Comment by MatthewDaggitt** [comment] 2023-10-20 02:08
How about we move everything in `README` into a new folder `README/Readme` and then add a new `README/standard-library-readme.agda-lib` file?

**Comment by jamesmckinna** [comment] 2023-10-20 03:48
I don't see this as a v2.0 issue *per se*, but a recurrent library design issue esp. for newcomers to library development... which I've learnt to live with, and which crucially, my emacs infrastructure has learnt to live with. 

There are a number of overlapping issues, I think:
* auto-generated (currently not, but that brings its own problems) or not; but some changes have even involved editing lists of filenames in`GenerateEverything`, so auto-generation is not a panacea as such; 
* the `-i.` flag (cf. Don Norman's  The Trouble With Unix, samizdat copies widely available) which I'm (now) fine with, but of the three machines I regularly do development work on, one of them consistently trips up over in interactive mode in emacs, and I have found it impossible to debug properly; 
* the general/ambient ecosystem engineering problem which @JacquesCarette in particular has drawn attention to eg regarding searchability/navigability in the library;
* others, perhaps also. 

I would prefer to open an 'ecosystem' issue, and add this specific issue to a shopping list there, because I think this lies beyond... our current near-release horizon. What I don't know is if it's a stdlib issue, or a main Agda issue... but it feels like the latter, even if library development seems to be where it's experienced most sharply?

**Comment by MatthewDaggitt** [comment] 2023-10-20 04:08
So I agree, there's a lot of issues that exist and yes please feel free to open new issues for the ones that are relevant to the standard library.

However the original reason for this issue is that the top-level `README.agda` file doesn't type-check currently, so I was purely focusing on how to fix that small technical problem with the tools we currently have available. I think that is within scope of v2.0 and easily deliverable with 30 minutes of work...

**Comment by shhyou** [comment] 2023-10-20 04:14
> I don't see this as a v2.0 issue _per se_, but a recurrent library design issue esp. for newcomers to library development... which I've learnt to live with, and which crucially, my emacs infrastructure has learnt to live with.
> 

Re the context from #2169: when an *end user* downloads the standard library (or perhaps installed together with Agda through some OS package manager), how should they load and use README[/＊].agda?

**Comment by jamesmckinna** [comment] 2023-10-20 06:11
Why doesn't it typecheck? Sorry to be obtuse. My 'quick' version of `make test` is to run (haskell RTS arguments for my machine suppressed)
```agda
agda -i. -isrc README.agda
```
and that (still) seems to work? I'll recheck when I'm awake.

**Comment by shhyou** [comment] 2023-10-20 06:19
It does with `-i.`! The issue is about stdlib users who open READMEs in Emacs. It's better if it just works without additional configuration, or that there are instructions in `installation-guide.md`.

**Comment by jamesmckinna** [comment] 2023-10-20 06:23
Yes. For some reason, my emacs setup does mean that all top-level modules typecheck. I'll try and find out how I fit that working...

**Comment by jamesmckinna** [comment] 2023-10-20 12:50
Given that my diagnosis above suggests the problem lies 'between' `agda-stdlib` (in any version), and the `agda` installation instructions (or `cabal`/`stack` install scripts), that this issue perhaps also requires input from the main agda-dev team and/or `readthedocs` editorial contributors. And, FWIW, given how slow I am at getting things done, it took me quite a bit more than 30mins to diagnose this! And I don't really know if my 'fix' works for anyone else...
... so: shout-outs to @andreasabel and @MatthewDaggitt for feedback/comments...

**Comment by jamesmckinna** [comment] 2023-10-21 16:16
> How about we move everything in `README` into a new folder `README/Readme` and then add a new `README/standard-library-readme.agda-lib` file?

Perhaps this is *a* solution to the problem, at least as concerns `README`, but I don't think it's robust wrt (new) users/developers wanting to experiment with things in `${AGDA_ROOT}/.` on top of the `${AGDA_ROOT}/src/` hierarchy of some particular version (incl. esp. the development version of the library), but find that they then can't typecheck things properly during interactive development in `emacs`. This is what I understand to be the 'real' issue here?

So, FWIW: :-1:  from me, sorry!

**Comment by MatthewDaggitt** [comment] 2023-10-22 03:27
I think there's been some miscommunication on my part about what I'm proposing. Let's discuss on Thursday :+1:

**Comment by jamesmckinna** [comment] 2023-10-22 21:05
It may also be that I have got the wrong end of the stick, and blundered on from a position of insufficient insight/understanding.

**Comment by MatthewDaggitt** [comment] 2023-10-30 05:34
Fixed by https://github.com/agda/agda-stdlib/pull/2184/

**Closed** 2023-11-05 01:47 UTC
Labels: upstream, admin
