### ISSUE TITLE
The deprecations in Reflection mention modules that don't exist

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1842] opened 2022-10-04 22:28 UTC
`Reflection.Term` has been moved to `Reflection.AST.Term`.
We need to update the deprecation messages to point to the right module.

**Comment by jamesmckinna** [comment] 2022-10-05 10:51
So... part of the problem is that these are 1.3-era deprecation messages.
One solution is to simply change all of these to the 'correct' positions, and flag them as v2.0 changes; but then what's the policy about 1.3-era changes? Are these being removed as part of the v2.0 release?

**Comment by jamesmckinna** [comment] 2022-10-05 11:50
And that's you self-assigning to this issue? or simply clarifying (sensible) policy? ;-)

**Comment by MatthewDaggitt** [comment] 2022-10-05 11:51
Just clarifying! (but happy to assign!)

**Comment by jamesmckinna** [comment] 2022-10-06 14:43
Done. PR #1845

**Closed** 2022-10-07 11:20 UTC
Labels: bug, deprecation
